param(
    [string]$InstallPath = "C:\Program Files (x86)\Nova1492",
    [string]$WorkingCopyPath = "",
    [switch]$PatchOriginalInstall,
    [switch]$RefreshWorkingCopy,
    [string]$LegPart = "legs7_hb",
    [string]$BodyPart = "body10_skdr",
    [string]$ArmPart = "arm29_sdbt"
)

$ErrorActionPreference = "Stop"

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot "..\..")
$artifactRoot = Join-Path $repoRoot "artifacts\nova1492\original-oracle"
$backupRoot = Join-Path $artifactRoot "backups"
$manifestPath = Join-Path $artifactRoot "active-oracle.json"

function Fail($message) {
    Write-Error $message
    exit 1
}

function Resolve-OraclePath([string]$Path) {
    if ([System.IO.Path]::IsPathRooted($Path)) {
        return [System.IO.Path]::GetFullPath($Path)
    }

    return [System.IO.Path]::GetFullPath((Join-Path $repoRoot $Path))
}

if (Test-Path $manifestPath) {
    Fail "An active original-oracle patch manifest already exists: $manifestPath. Run tools\nova1492\Restore-Nova1492OriginalOracle.ps1 before starting another oracle session."
}

if (!(Test-Path $InstallPath)) {
    Fail "Nova1492 install path was not found: $InstallPath"
}

New-Item -ItemType Directory -Force -Path $artifactRoot | Out-Null
New-Item -ItemType Directory -Force -Path $backupRoot | Out-Null

$sourceInstallPath = (Resolve-Path $InstallPath).Path
$targetInstallPath = $sourceInstallPath

if (!$PatchOriginalInstall) {
    if ([string]::IsNullOrWhiteSpace($WorkingCopyPath)) {
        $WorkingCopyPath = Join-Path $artifactRoot "install-copy"
    }

    $targetInstallPath = Resolve-OraclePath $WorkingCopyPath
    $artifactRootFull = Resolve-OraclePath $artifactRoot

    if (!$targetInstallPath.StartsWith($artifactRootFull, [System.StringComparison]::OrdinalIgnoreCase)) {
        Fail "Working copy path must stay inside artifact root. Target: $targetInstallPath Root: $artifactRootFull"
    }

    $needsCopy = !(Test-Path $targetInstallPath) -or $RefreshWorkingCopy
    if ($needsCopy) {
        New-Item -ItemType Directory -Force -Path $targetInstallPath | Out-Null
        & robocopy $sourceInstallPath $targetInstallPath /MIR /R:2 /W:1 /NFL /NDL /NJH /NJS /NP | Out-Host
        if ($LASTEXITCODE -gt 7) {
            Fail "Failed to create Nova1492 working copy. Robocopy exit code: $LASTEXITCODE"
        }
    }
}

$scenePath = Join-Path $targetInstallPath "datan\common\SceneLobby.js"
$exePath = Join-Path $targetInstallPath "Nova1492.exe"

if (!(Test-Path $scenePath)) {
    Fail "SceneLobby.js was not found: $scenePath"
}

if (!(Test-Path $exePath)) {
    Fail "Nova1492.exe was not found: $exePath"
}

$stamp = Get-Date -Format "yyyyMMdd-HHmmss"
$backupPath = Join-Path $backupRoot "SceneLobby.js.$stamp.bak"
Copy-Item -LiteralPath $scenePath -Destination $backupPath -Force

$oracleScript = @"
// JG original assembly oracle session.
// This file is generated by Start-Nova1492OriginalOracle.ps1 and must be restored
// with Restore-Nova1492OriginalOracle.ps1 after capture/review.

var viewer = new ModelViewer();
viewer.resize((1024 - 768) / 2, 0, 768, 768);
viewer.scene = new UnitModel("$LegPart", "$BodyPart", "$ArmPart");

var cam = viewer.camera;
cam.target.set(0, 0.5, 0, 1);
viewer.scene.matrix.rotateY(Math.PI / 5);
var camRotY = Math.PI / 4;
var zoom = 1;
var originalDistance = 5;

viewer.onmbuttonup = function () {
    var dx = mouse.mstartX - mouse.x;
    var dy = mouse.mstartY - mouse.y;
    if (dx * dx + dy * dy < 10) {
        zoom = 1;
        viewer.onwheel(0, 0, 0);
        cam.target.x = 0;
        cam.target.y = 0.5;
    }
};

viewer.onwheel = function (x, y, delta) {
    zoom *= Math.pow(1.001, delta);
    updateCamera();
};

scene.attach(viewer);

var rotateY = 0;
var rotateX = 0.005;

scene.ondraw = function () {
    ctx.__novaFont.fill("JG oracle: $LegPart + $BodyPart + $ArmPart", 10, 100);
    ctx.__novaFont.fill("Zoom: " + zoom.toFixed(3), 10, 122);

    if (mouse.mbutton && !mouse.mpress) {
        cam.target.x += mouse.deltaX / -200 / zoom;
        cam.target.y += mouse.deltaY / 200 / zoom;
    }
    if ((mouse.lbutton && !mouse.lpress) ||
        (mouse.rbutton && !mouse.rpress)) {
        rotateX = mouse.deltaX / 300;
        rotateY = mouse.deltaY / 300;
    }
    camRotY += rotateY;
    var lim = Math.PI / 2 - 0.01;
    if (camRotY > lim) {
        camRotY = lim;
    } else if (camRotY < -lim) {
        camRotY = -lim;
    }

    rotateY *= 0.75;
    viewer.scene.matrix.rotateY(rotateX);
    updateCamera();
};

function updateCamera() {
    var ndist = originalDistance / zoom;
    var campos = cam.position;
    campos.x = 0;
    campos.z = Math.cos(camRotY) * ndist;
    campos.y = Math.sin(camRotY) * ndist;
    campos.w = 0;
    campos.add(cam.target);
    cam.far = ndist * 2 + 100;
    cam.near = ndist / 100;
}
"@

try {
    Set-Content -LiteralPath $scenePath -Value $oracleScript -Encoding UTF8
} catch {
    try {
        Copy-Item -LiteralPath $backupPath -Destination $scenePath -Force
    } catch {
        Fail "Failed to patch SceneLobby.js and failed to restore backup. Scene: $scenePath Backup: $backupPath Error: $($_.Exception.Message)"
    }
    Fail "Failed to patch SceneLobby.js; restored backup. $($_.Exception.Message)"
}

$proc = Start-Process -FilePath $exePath -WorkingDirectory $targetInstallPath -PassThru

$manifest = [ordered]@{
    sourceInstallPath = $sourceInstallPath
    targetInstallPath = $targetInstallPath
    patchOriginalInstall = [bool]$PatchOriginalInstall
    scenePath = $scenePath
    backupPath = $backupPath
    exePath = $exePath
    processId = $proc.Id
    startedAt = (Get-Date).ToString("o")
    legPart = $LegPart
    bodyPart = $BodyPart
    armPart = $ArmPart
    restoreCommand = "powershell -NoProfile -ExecutionPolicy Bypass -File tools\nova1492\Restore-Nova1492OriginalOracle.ps1"
}

$manifest | ConvertTo-Json -Depth 4 | Set-Content -LiteralPath $manifestPath -Encoding UTF8

if ($PatchOriginalInstall) {
    Write-Host "Patched original SceneLobby.js for UnitModel oracle."
} else {
    Write-Host "Patched Nova1492 working copy SceneLobby.js for UnitModel oracle."
    Write-Host "Source install remains unchanged: $sourceInstallPath"
    Write-Host "Working copy: $targetInstallPath"
}
Write-Host "Combo: $LegPart + $BodyPart + $ArmPart"
Write-Host "Backup: $backupPath"
Write-Host "Manifest: $manifestPath"
Write-Host "Nova1492 PID: $($proc.Id)"
Write-Host "Restore after capture/review:"
Write-Host "  powershell -NoProfile -ExecutionPolicy Bypass -File tools\nova1492\Restore-Nova1492OriginalOracle.ps1"
